### ISSUE TITLE
[Epic] panel account system design

### ISSUE THREAD

**Issue by DemoHn** [DemoHn/obsidian-panel#43]
Since `obsidian-panel` is designed to provide services to multiple users with different permission, a plan `account-system` should be discussed and on plan.

This epic and be split to several subtopics (or questions):

- [ ] Roles definition: `Server owner`, `Panel Admin`, `Panel User`, `Visitor`, etc?
- [x] How to register a `panel admin`?
- [ ] How to design user login event?
- [ ] How to define resources to access for each role?
